# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\x07\n\x05\x45mpty\"I\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"A\n\x0cTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\"E\n\x0bTaskSummary\x12\x13\n\x0b\x61\x64\x64\x65\x64_count\x18\x01 \x01(\x05\x12\x10\n\x08task_ids\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x86\x01\n\nTaskUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tcompleted\x18\x04 \x01(\x08H\x02\x88\x01\x01\x42\x08\n\x06_titleB\x0e\n\x0c_descriptionB\x0c\n\n_completed\"B\n\x12TaskUpdateResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\xdc\x01\n\x0bTodoService\x12+\n\x07\x41\x64\x64Task\x12\n.todo.Task\x1a\x12.todo.TaskResponse\"\x00\x12(\n\tListTasks\x12\x0b.todo.Empty\x1a\n.todo.Task\"\x00\x30\x01\x12\x35\n\x10\x41\x64\x64MultipleTasks\x12\n.todo.Task\x1a\x11.todo.TaskSummary\"\x00(\x01\x12?\n\x0bUpdateTasks\x12\x10.todo.TaskUpdate\x1a\x18.todo.TaskUpdateResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_TASK']._serialized_start=29
  _globals['_TASK']._serialized_end=102
  _globals['_TASKRESPONSE']._serialized_start=104
  _globals['_TASKRESPONSE']._serialized_end=169
  _globals['_TASKSUMMARY']._serialized_start=171
  _globals['_TASKSUMMARY']._serialized_end=240
  _globals['_TASKUPDATE']._serialized_start=243
  _globals['_TASKUPDATE']._serialized_end=377
  _globals['_TASKUPDATERESPONSE']._serialized_start=379
  _globals['_TASKUPDATERESPONSE']._serialized_end=445
  _globals['_TODOSERVICE']._serialized_start=448
  _globals['_TODOSERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
