# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_pb2 as todo__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in todo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TodoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/todo.TodoService/AddTask',
                request_serializer=todo__pb2.Task.SerializeToString,
                response_deserializer=todo__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_stream(
                '/todo.TodoService/ListTasks',
                request_serializer=todo__pb2.Empty.SerializeToString,
                response_deserializer=todo__pb2.Task.FromString,
                _registered_method=True)
        self.AddMultipleTasks = channel.stream_unary(
                '/todo.TodoService/AddMultipleTasks',
                request_serializer=todo__pb2.Task.SerializeToString,
                response_deserializer=todo__pb2.TaskSummary.FromString,
                _registered_method=True)
        self.UpdateTasks = channel.stream_stream(
                '/todo.TodoService/UpdateTasks',
                request_serializer=todo__pb2.TaskUpdate.SerializeToString,
                response_deserializer=todo__pb2.TaskUpdateResponse.FromString,
                _registered_method=True)


class TodoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTask(self, request, context):
        """Unary RPC: Add a single task and get a response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Server streaming RPC: Get all tasks as a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMultipleTasks(self, request_iterator, context):
        """Client streaming RPC: Add multiple tasks in a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTasks(self, request_iterator, context):
        """Bidirectional streaming RPC: Update multiple tasks and get updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=todo__pb2.Task.FromString,
                    response_serializer=todo__pb2.TaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=todo__pb2.Empty.FromString,
                    response_serializer=todo__pb2.Task.SerializeToString,
            ),
            'AddMultipleTasks': grpc.stream_unary_rpc_method_handler(
                    servicer.AddMultipleTasks,
                    request_deserializer=todo__pb2.Task.FromString,
                    response_serializer=todo__pb2.TaskSummary.SerializeToString,
            ),
            'UpdateTasks': grpc.stream_stream_rpc_method_handler(
                    servicer.UpdateTasks,
                    request_deserializer=todo__pb2.TaskUpdate.FromString,
                    response_serializer=todo__pb2.TaskUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo.TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todo.TodoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todo.TodoService/AddTask',
            todo__pb2.Task.SerializeToString,
            todo__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/todo.TodoService/ListTasks',
            todo__pb2.Empty.SerializeToString,
            todo__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMultipleTasks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/todo.TodoService/AddMultipleTasks',
            todo__pb2.Task.SerializeToString,
            todo__pb2.TaskSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTasks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/todo.TodoService/UpdateTasks',
            todo__pb2.TaskUpdate.SerializeToString,
            todo__pb2.TaskUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
